// ACTIONS FOR ACTIONS
export const GET_ACTIONS_LOADING='GET_ACTIONS_LOADING';
export const GET_ACTIONS_SUCCESS='GET_ACTIONS_SUCCESS';
export const GET_ACTIONS_ERROR='GET_ACTIONS_ERROR';

// ACTIONS FOR ALERTS
export const GET_ALERTS_LOADING='GET_ALERTS_LOADING';
export const GET_ALERTS_SUCCESS='GET_ALERTS_SUCCESS';
export const GET_ALERTS_ERROR='GET_ALERTS_ERROR';
