// ACTIONS FOR ACTIONS
export const INITIAL_EVENTS='INITIAL_EVENTS';

// ACTIONS FOR ALERTS
export const GET_ALERT_LOADING='GET_ALERT_LOADING';
export const GET_ALERT_SUCCESS='GET_ALERT_SUCCESS';
export const GET_ALERT_ERROR='GET_ALERT_ERROR';
